### ISSUE TITLE
Unable to compile on Centos 5.4

### ISSUE THREAD

**Issue by mrbahr2003** [pornel/pngquant#17]
Hi,

I am trying to compile your latest version on Centos and am unable to.

[root@sydney pornel-improved-pngquant-0af1c98]# make
gcc -DNDEBUG -Wall -Wno-unknown-pragmas -I. -I../libpng -I../zlib -I/usr/local/include/ -I/usr/include/ -I/usr/X11/include/ -O3 -mtune=native -fearly-inlining -fstrict-aliasing -ffast-math -funroll-loops -fstrict-overflow -fomit-frame-pointer -momit-leaf-frame-pointer -ffinite-math-only -fno-trapping-math -funsafe-loop-optimizations -std=c99    -c -o pngquant.o pngquant.c
cc1: error: unrecognized command line option "-fstrict-overflow"
pngquant.c:1: error: bad value (native) for -mtune= switch
make: **\* [pngquant.o] Error 1

I've removed both -mtune and -fstrict-overflow from the makefile, but then when I try to compile, I get a number of errors.  The initial one is:

[root@sydney pornel-improved-pngquant-0af1c98]# make
gcc -DNDEBUG -Wall -Wno-unknown-pragmas -I. -I../libpng -I../zlib -I/usr/local/include/ -I/usr/include/ -I/usr/X11/include/ -O3 -fearly-inlining -fstrict-aliasing -ffast-math -funroll-loops -fomit-frame-pointer -momit-leaf-frame-pointer -ffinite-math-only -fno-trapping-math -funsafe-loop-optimizations -std=c99    -c -o pngquant.o pngquant.c
In file included from pngquant.c:56:
rwpng.h:35:57: error: png.h: No such file or directory
In file included from pngquant.c:56:
rwpng.h:60: error: expected specifier-qualifier-list before ‘png_uint_32’
rwpng.h:70: error: expected specifier-qualifier-list before ‘png_uint_32’

I don't know if png.h is supposed to be included in the distribution or it should already be on the system.  Can you please let me know what the dependencies are?

I think this is a brilliant program and I'd like to use it.

Thanks,
Tom
